/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ftn_krt_mdb_Djb2RA502012 */

#ifndef _Included_com_ftn_krt_mdb_Djb2RA502012
#define _Included_com_ftn_krt_mdb_Djb2RA502012
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ftn_krt_mdb_Djb2RA502012
 * Method:    getHashRA502012
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_ftn_krt_mdb_Djb2RA502012_getHashRA502012
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
